# Framework 13 laptop configuration
{ config, pkgs, lib, inputs, local, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # System modules
    ../../modules/nixos/base.nix
    ../../modules/nixos/niri.nix
    ../../modules/nixos/applications.nix
    ../../modules/nixos/framework.nix
  ];

  # System hostname
  networking.hostName = local.hostname;

  # Localization
  # Timezone is handled by automatic-timezoned service
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # Console keyboard
  console.keyMap = "us";

  # User account
  users.users.${local.username} = {
    isNormalUser = true;
    description = local.fullName;
    extraGroups = [ "wheel" "networkmanager" "video" "audio" "input" "docker" ];
    shell = pkgs.zsh;
    hashedPassword = local.hashedPassword;
  };

  # Home Manager configuration for the user
  home-manager.users.${local.username} = import ../../modules/home;

  # Firmware
  hardware.enableRedistributableFirmware = true;
  hardware.enableAllFirmware = true;

  # This value determines the NixOS release
  system.stateVersion = "24.11";
}
