# Local configuration - generated by install.sh
# This file contains machine-specific settings
{
  # User account
  username = "user";
  fullName = "User";
  hashedPassword = "";  # Generate with: mkpasswd -m sha-512

  # System
  hostname = "framework";

  # Git identity (for Home Manager)
  gitUsername = "";
  gitEmail = "";
}
