# Machine-specific configuration
# This file is auto-generated by install.sh during installation
# For CI/testing purposes, this provides example values
{
  username = "nixos";
  fullName = "NixOS User";
  hostname = "framework";
  gitUsername = "nixos";
  gitEmail = "nixos@example.com";
  # Example password hash for "changeme"
  # Generate your own with: mkpasswd -m sha-512
  hashedPassword = "$6$rounds=65536$saltsaltsalt$IvaHiRkzSKkbj.FBR6bPwHUb9RRcT6bXB6HWF3RH.lJmxlLX0eLELXLEBJXALMKGOKXOVXMLAMBCDBEFGH";
}
